swagger: '2.0'
info:
  version: "1.0"
  title: Burning Flipside Registration System API
  description: "This is the api to access theme camp, art project, art car, and event registration for Burning Flipside"
  contact:
    name: Technology Team
    email: technology@burningflipside.com
host: secure.burningflipside.com
basePath: /register/api/v1
schemes:
    - https
paths:
  /art:
    get:
      tags:
        - Art
      summary: Gets `ArtProject` objects.
      description: Gets `ArtProject` objects for the current year.
      security:
        - flipside_auth:
          - read:registration
    post:
      tags: ["Art"]
      summary: Create a new `ArtProject` object.
      description: Creates a new `ArtProject` object owned by the calling user and for the current year.
      security: [
          flipside_auth: ["write:registration"]
        ]
  /art/{artId}:
    get:
      tags: ["Art"]
      summary: Obtains the specified `ArtProject` object.
      description: Obtains the `ArtProject` object with the specified ID.
      security: [
          flipside_auth: ["read:registration"]
        ]
    put:
      tags: ["Art"]
      summary: Modifies the specified `ArtProject` object.
      description: Modifies the `ArtProject` object with the specified ID if the user has the rights to do so.
      security: [
          flipside_auth: ["write:registration"]
        ]
    delete:
      tags: ["Art"]
      summary: Deletes the specified `ArtProject` object.
      description: Deletes the `ArtProject` object with the specified ID if the user has the rights to do so.
      security: [
          flipside_auth: ["write:registration"]
        ]
  /art/{artId}/contact:
    post:
      tags: ["Art"]
      summary: Sends an email to the lead of the `ArtProject` object.
      description: Sends an email to the person specified as the lead in the `ArtProject` object with the user's email as reply-to.
      security: [
          flipside_auth: ["write:registration"]
        ]
  /camps:
    get:
      tags: ["Theme Camps"]
      summary: Gets `ThemeCamp` objects.
      description: Gets `ThemeCamp` objects for the current year.
      security: [
          flipside_auth: ["read:registration"]
        ]
    post:
      tags:
        - Theme Camps
      summary: Create a new `ThemeCamp` object.
      description: Creates a new `ThemeCamp` object owned by the calling user and for the current year.
      security:
          - flipside_auth:
            - write:registration
  /camps/{campId}:
    get:
      tags:
        - Theme Camps
      summary: Obtains the specified `ThemeCamp` object.
      description: Obtains the `ThemeCamp` object with the specified ID.
      security:
          - flipside_auth:
            - read:registration
    put:
      tags:
        - Theme Camps
      summary: Modifies the specified `ThemeCamp` object.
      description: Modifies the `ThemeCamp` object with the specified ID if the user has the rights to do so.
      security:
          - flipside_auth:
            - write:registration
    delete:
      tags:
        - Theme Camps
      summary: Deletes the specified `ThemeCamp` object.
      description: Deletes the `ThemeCamp` object with the specified ID if the user has the rights to do so.
      security:
          - flipside_auth:
            - write:registration
  /camps/{campId}/contact:
    post:
      tags:
        - Theme Camps
      summary: Sends an email to the lead of the `ThemeCamp` object.
      description: Sends an email to the person specified as the lead in the `ThemeCamp` object with the user's email as reply-to.
      security:
          - flipside_auth:
            - write:registration
  /dmv:
    get:
      tags:
        - DMV
      summary: Gets `ArtCar` objects.
      description: Gets `ArtCar` objects for the current year.
      security:
          - flipside_auth:
            - read:registration
    post:
      tags:
        - DMV
      summary: Create a new `ArtCar` object.
      description: Creates a new `ArtCar` object owned by the calling user and for the current year.
      security:
          - flipside_auth:
            - write:registration
  /dmv/{carId}:
    get:
      tags:
        - DMV
      summary: Obtains the specified `ArtCar` object.
      description: Obtains the `ArtCar` object with the specified ID.
      security:
          - flipside_auth:
            - read:registration
    put:
      tags:
        - DMV
      summary: Modifies the specified `ArtCar` object.
      description: Modifies the `ArtCar` object with the specified ID if the user has the rights to do so.
      security:
          - flipside_auth:
            - write:registration
    delete:
      tags:
        - DMV
      summary: Deletes the specified `ArtCar` object.
      description: Deletes the `ArtCar` object with the specified ID if the user has the rights to do so.
      security:
          - flipside_auth:
            - write:registration
  /event:
    get:
      tags:
        - Events
      summary: Gets `Event` objects.
      description: Gets `Event` objects for the current year.
      security:
          - flipside_auth:
            - read:registration
    post:
      tags:
        - Events
      summary: Create a new `Event` object.
      description: Creates a new `Event` object owned by the calling user and for the current year.
      security:
          - flipside_auth:
            - write:registration
  /event/{eventId}:
    get:
      tags:
        - Events
      summary: Obtains the specified `Event` object.
      description: Obtains the `Event` object with the specified ID.
      security:
          - flipside_auth:
            - read:registration
    put:
      tags:
        - Events
      summary: Modifies the specified `Event` object.
      description: Modifies the `Event` object with the specified ID if the user has the rights to do so.
      security:
          - flipside_auth:
            - write:registration
    delete:
      tags:
        - Events
      summary: Deletes the specified `Event` object.
      description: Deletes the `Event` object with the specified ID if the user has the rights to do so.
      security:
          - flipside_auth:
            - write:registration
securityDefinitions:
  "flipside_auth":
    type: "oauth2"
    flow: "accessCode"
    authorizationUrl: "https://profiles.burningflipside.com/OAUTH2/authorize.php"
    tokenUrl: "https://profiles.burningflipside.com/OAUTH2/token.php"
    scopes:
      "read:registration": "read regisration information"
      "write:registration": "modify or create registration information"